### ISSUE TITLE
BLD: future change of behaviour in pip

### ISSUE THREAD

**Issue by neutrinoceros** [pyx-project/pyx#41] opened 2022-11-19 20:37 UTC
Installing pyx from source within a fresh environment as
```
python -m pip install -U pip
python -m pip install pyx
```

yields
```
DEPRECATION: pyx is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
```

**Comment by neutrinoceros** [comment] 2023-07-31 08:10
Publishing a wheel would also resolve the issue for dependees.
I'm willing to help implementing either (or both) solutions.

**Comment by joerg-lehmann** [comment] 2023-09-23 15:08
Thanks for reporting. We have now moved to a pyproject.toml (in commit 26c45767514413de4a21a443912a8a44b8682f82) for the project metadata. This seems to work as intended, however, we had problems with our build dependencies (pip did not recognize them as optional-dependencies in the pyproject.toml). As a temporary solutions these ones have been moved to dev_requirements.txt.

**Comment by joerg-lehmann** [comment] 2023-09-23 15:09
Closing this issue.

**Closed as completed by joerg-lehmann** 2023-09-23 15:09 UTC
